from PIL import Image
import numpy as np
from PIL import ImageChops
import matplotlib.pyplot as plt

# zadanie 1a
obraz1 = Image.open('obraz1.png')
print("tryb obraz1: ",obraz1.mode)
obraz2 = obraz1.copy().convert('RGB')

# zadanie 1b
r,g,b,a = obraz1.split()
# a.show()
obraz3 = Image.new('RGB', obraz1.size, (255,255,255))
obraz3.paste(obraz1, (0, 0), a)
obraz3.save('obraz3.png')

# zadanie 1c
plt.figure(figsize=(10,6))
plt.subplot(1,3,1)
plt.imshow(obraz2)
plt.title("metoda .convert")
plt.axis('off')
plt.subplot(1,3,2)
plt.imshow(obraz3)
plt.title("metoda .paste")
plt.axis('off')
plt.subplot(1,3,3)
plt.imshow(ImageChops.difference(obraz2,obraz3))
plt.title("różnice między metodami")
plt.axis('off')
plt.show()
#-------------------------------------------------------
# zadanie 2a
tryby = ['CMYK','YCbCr','HSV']
plt.figure(figsize=(10,6))
plt.subplot(1,3,1)
plt.imshow(obraz1.convert('CMYK'))
plt.title("CMYK")
plt.axis('off')
plt.subplot(1,3,2)
plt.imshow(obraz1.convert('YCbCr'))
plt.title("YCbCr")
plt.axis('off')
plt.subplot(1,3,3)
plt.imshow(obraz1.convert('HSV'))
plt.title("HSV")
plt.axis('off')
plt.savefig('fig1.png')
# plt.show()

# zadanie 2b
c,m,y,k = obraz1.convert('CMYK').split()
plt.figure(figsize=(10,6))
plt.subplot(2,2,1)
plt.imshow(c,'gray')
plt.title("kanał Cyan")
plt.axis('off')
plt.subplot(2,2,2)
plt.imshow(m,'gray')
plt.title("Kanał Magenta")
plt.axis('off')
plt.subplot(2,2,3)
plt.imshow(y,'gray')
plt.title("Kanał Yellow")
plt.axis('off')
plt.subplot(2,2,4)
plt.imshow(k,'gray')
plt.title("Kanał Key")
plt.axis('off')
plt.savefig('cmyk.png')
# plt.show()

y, cb, cr = obraz1.convert('YCbCr').split()
plt.figure(figsize=(10,6))
plt.subplot(1,3,1)
plt.imshow(y,'gray')
plt.title("kanał Luminance")
plt.axis('off')
plt.subplot(1,3,2)
plt.imshow(cb,'gray')
plt.title("Kanał Chroma Blue")
plt.axis('off')
plt.subplot(1,3,3)
plt.imshow(cr,'gray')
plt.title("Kanał Chroma Red")
plt.axis('off')
plt.savefig('ycbcr.png')
# plt.show()

h,s,v = obraz1.convert('HSV').split()
plt.figure(figsize=(10,6))
plt.subplot(1,3,1)
plt.imshow(h,'gray')
plt.title("kanał Hue")
plt.axis('off')
plt.subplot(1,3,2)
plt.imshow(s,'gray')
plt.title("Kanał Saturation")
plt.axis('off')
plt.subplot(1,3,3)
plt.imshow(v,'gray')
plt.title("Kanał Value/Intensity")
plt.axis('off')
plt.savefig('hsv.png')
# plt.show()
#-----------------------------------------------
# zadanie 3a
obraz4 = Image.open('obraz4.jpg')
print("tryb obraz4: ",obraz4.mode)
obraz4 = obraz4.resize(obraz1.size, 1)
obraz4a = obraz4.copy()
obraz4a.paste(obraz1, (0,0), a)
obraz4a.show()
obraz1a = obraz1.copy()
obraz1a.paste(obraz4, (0,0), a)
obraz1a.show()
plt.figure(figsize=(5,3))
plt.subplot(1,2,1)
plt.imshow(obraz4a)
plt.title('obraz1 na obraz4')
plt.axis('off')
plt.subplot(1,2,2)
plt.imshow(obraz1a)
plt.title('obraz4 na obraz1')
plt.axis('off')
plt.savefig('fig2.png')
plt.show()



